### ISSUE TITLE
improve image processing

### ISSUE THREAD

**Issue by nmchale** [FishyByte/SushiRNG#10]
Improve tracking quality of OpenCV.  Increase tracking accuracy and increase  the objects lifetime

**Comment by c-asakawa** [comment]
### tasks
- **increase tracking accuracy**
  - tweak color range to work with a broader range of colors (depending on time of day, etc)
  - find the optimal contour size remove false positives
- **increase objects lifetime**
  - experiment with tracking fishes individually
  - add timers for acceptable object lifetime

**Comment by c-asakawa** [comment]
completed individual fish tracking

**Comment by c-asakawa** [comment]
todo: create conditional checks to ensure its the same object being tracked. this could be done by creating a limit on the `x_previous` and `x_current` values, this will also reduce the bit per second we are receiving

**Comment by c-asakawa** [comment]
previous implementation created two many runs, so now the tracking algorithm tracks velocity and acceleration to flip the outcome of the bit depending on a hard coded threshold value.
