### ISSUE TITLE
add 8-ball response strings

### ISSUE THREAD

**Issue by obriematt** [FishyByte/SushiRNG#39]
The 8-Ball responses are currently unbalanced. 

Currently implementation takes a 5 bit binary number in to determine response. 11111 == 31 but only 20 responses. If the corresponding digit is greater than 19 it will respond with "Lol no". 11 out of 31 possible answers are "Lol no". Need to rework the code for balanced responses.

**Comment by aingc** [comment]
Simply modding 20 for the binary number of 0 - 31 won't be enough since it'll be weighed towards the first 11 responses. We're gonna have to drop it down to 16 responses, OR make 32 responses in total.

Unless we can generate a decimal number from a specified range

**Comment by c-asakawa** [comment]
none of the above comments are relevant anymore, i solved this by writing a route for the back end to return an integer with a specific range, so i can have any number of responses, no mod problem anymore. 

i'll make sure the http GET request is dynamic to grab the max value of the range automatically, so you literally only need to put those new requests in the array, and thats it.

**Comment by c-asakawa** [comment]
opps didn't mean to close it there
